<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Wupa.GuiLayoutTests</StartupObject>
    <ApplicationIcon>../../Gui/Assets/WUPA.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../Gui/Assets/WUPA-256.png" LogicalName="Wupa.BrandLogo" />
    <Compile Include="../../Gui/Program.cs" Link="ProductionGui.cs" />
    <Compile Include="../../Gui/UpdateCore.cs" Link="UpdateCore.cs" />
    <Compile Include="../../Gui/UpdatesUI.cs" Link="UpdatesUI.cs" />
    <Compile Include="../../Gui/ReportCompletion.cs" Link="ReportCompletion.cs" />
    <EmbeddedResource Include="../../Gui/Assets/UpdatePublicKey.pem" LogicalName="Wupa.UpdatePublicKey" />
  </ItemGroup>
</Project>
